version: '3.8'
services:
  # db:
    # container_name: pg_container
    # image: postgres
    # restart: always
    # environment:
      # POSTGRES_USER: root
      # POSTGRES_PASSWORD: root
      # POSTGRES_DB: test_db
    # ports:
      # - "5432:5432"
  db:
    container_name: postgis_container
    image: postgis/postgis
    restart: on-failure
    environment:
      POSTGRES_DB: postgis
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      ALLOW_IP_RANGE: 0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      POSTGRES_MULTIPLE_EXTENSIONS: postgis,hstore,postgis_topology,postgis_raster,pgrouting
    ports:
      - "15432:5432"
    healthcheck:
      test: "exit 0"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"